services:
  api:
    build: .
    container_name: zebrands-products-service
    ports:
      - "8001:8000"
    env_file:
      - .env

    networks:
      - zebrands-net


networks:
  zebrands-net:
    external: true